Repository bank-vaults/vault-secrets-webhook, pull requests merged in 2024-05, with the labels that each got.

#410 ci: update dependabot config
  .github/dependabot.yaml
Labels: size/S, area/pipeline

#390 fix: incorrect behavior when using servingCertificate without CertManager #389
  deploy/charts/vault-secrets-webhook/templates/webhook-cert-manager.yaml
Labels: kind/bug, size/XS, area/build

#428 chore: update nix
  flake.lock
  flake.nix
  main.go
  pkg/webhook/registry.go
  tlscertificate.go
Labels: size/M, area/dependencies, area/provider/vault, area/pipeline

#422 fix: mutate containers with a startup probe
  pkg/webhook/pod.go
  pkg/webhook/pod_test.go
Labels: kind/enhancement, size/M, area/build
