Repository bank-vaults/vault-secrets-webhook, pull requests merged in 2024-02, with the labels that each got.

#275 chore: add options for resource requests for vault-agent
  pkg/webhook/config.go
  pkg/webhook/pod.go
  pkg/webhook/pod_test.go
Labels: size/S, area/artifacts

#327 fix: vault-log-level overwritten in pods
  pkg/webhook/pod.go
  pkg/webhook/pod_test.go
Labels: size/M

#337 chore: update bank-vaults deps
  .licensei.toml
  go.mod
  go.sum
Labels: size/XL

#341 feat: Cancel previous workflow on push
  .github/workflows/ci.yaml
Labels: size/XS

#340 refactor: export annotations
  pkg/webhook/common.go
  pkg/webhook/config.go
Labels: size/M

#347 refactor: factor out common package
  deploy/charts/vault-secrets-webhook/README.md
  pkg/common/common.go
  pkg/webhook/config.go
  pkg/webhook/configmap.go
  pkg/webhook/object.go
  pkg/webhook/pod.go
  pkg/webhook/secret.go
  pkg/webhook/webhook.go
Labels: size/M, kind/feature

#348 chore: bump versions for releases
  .github/workflows/ci.yaml
  deploy/charts/vault-secrets-webhook/README.md
  deploy/charts/vault-secrets-webhook/values.yaml
  docker-compose.yaml
  e2e/deploy/vault-secrets-webhook/values.yaml
  e2e/deploy/vault/vault.yaml
  e2e/main_test.go
  garden.yaml
Labels: size/S
